query device_info($device: String!) {
  DcimDevice(name__value: $device) {
    edges {
      node {
        id
        name {
          value
        }
        interfaces {
          edges {
            node {
              id
              mtu {
                value
              }
              name {
                value
              }
              description {
                value
              }
              role {
                value
              }
              status {
                value
              }
              ... on InterfacePhysical {
                untagged_vlan {
                  node {
                    vlan_id {
                      value
                    }
                    name {
                      value
                    }
                  }
                }
                l2_mode {
                  value
                }
                tagged_vlan {
                  edges {
                    node {
                      vlan_id {
                        value
                      }
                      name {
                        value
                      }
                    }
                  }
                }
                ip_addresses {
                  edges {
                    node {
                      address {
                        value
                      }
                    }
                  }
                }
              }
            }
          }
        }
        location {
          node {
            display_label
            vlans {
              edges {
                node {
                  vlan_id {
                    value
                  }
                  role {
                    value
                  }
                  name {
                    value
                  }
                  prefixes {
                    edges {
                      node {
                        gateway {
                          node {
                            address {
                              value
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
        primary_address {
          node {
            address {
              value
              ip
            }
            ip_prefix {
              node {
                ... on IpamPrefix {
                  id
                  gateway {
                    node {
                      address {
                        value
                        ip
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}